version: '2'

services:
  elasticsearch-node-1:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elasticsearch/config/elasticsearch-node-1.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/config/IKAnalyzer.cfg.xml:/usr/share/elasticsearch/plugins/ik/config/IKAnalyzer.cfg.xml:ro #修改ik分詞字典設定
      - ./data/node-1:/usr/share/elasticsearch/data # 放置persist Elasticsearch data 位置，避免刪除container之後資料不見
      - ./log/node-1:/usr/share/elasticsearch/log
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always
    environment:
      ES_JAVA_OPTS: "-Xmx1g -Xms1g" #依需求調整記憶體大小
    ulimits: # 禁止 swap
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk
    logging: 
      driver: "json-file"
      options: 
        max-size: "100m"
  elasticsearch-node-2:
      build:
        context: elasticsearch/
        args:
          ELK_VERSION: $ELK_VERSION
      volumes:
        - ./elasticsearch/config/elasticsearch-node-2.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
        - ./elasticsearch/config/IKAnalyzer.cfg.xml:/usr/share/elasticsearch/plugins/ik/config/IKAnalyzer.cfg.xml:ro #修改ik分詞字典設定
        - ./data/node-2:/usr/share/elasticsearch/data # 放置persist Elasticsearch data 位置，避免刪除container之後資料不見
        - ./log/node-2:/usr/share/elasticsearch/log
      ports:
        - "9202:9200"
        - "9302:9300"
      restart: always
      environment:
        ES_JAVA_OPTS: "-Xmx1g -Xms1g" #依需求調整記憶體大小
      ulimits:
        memlock:
          soft: -1
          hard: -1
      networks:
        - elk
      logging: 
        driver: "json-file"
        options: 
          max-size: "100m"
  elasticsearch-node-3:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elasticsearch/config/elasticsearch-node-3.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/config/IKAnalyzer.cfg.xml:/usr/share/elasticsearch/plugins/ik/config/IKAnalyzer.cfg.xml:ro #修改ik分詞字典設定
      - ./data/node-3:/usr/share/elasticsearch/data # 放置persist Elasticsearch data 位置，避免刪除container之後資料不見
      - ./log/node-3:/usr/share/elasticsearch/log
    ports:
      - "9203:9200"
      - "9303:9300"
    restart: always
    environment:
      ES_JAVA_OPTS: "-Xmx1g -Xms1g" #依需求調整記憶體大小
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk
    logging: 
      driver: "json-file"
      options: 
        max-size: "100m"
  # logstash:
  #   build:
  #     context: logstash/
  #     args:
  #       ELK_VERSION: $ELK_VERSION
  #   volumes:
  #     - ./logstash/config:/usr/share/logstash/config:ro
  #     - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
  #     - ./logstash/log:/var/log/logstash:ro
  #   ports:
  #     - "5011:5011"
  #   environment:
  #     LS_JAVA_OPTS: "-Xmx1g -Xms1g"
  #   networks:
  #     - elk
  #   depends_on:
  #     - elasticsearch
  #   logging: 
  #     driver: "json-file"
  #     options: 
  #       max-size: "100m"

  kibana:
    build:
      context: kibana/
      args:
        KIBANA_VERSION: $KIBANA_VERSION
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch-node-1
      - elasticsearch-node-2
      - elasticsearch-node-3
    logging: 
      driver: "json-file"
      options: 
        max-size: "100m"

networks:
  elk:
    driver: bridge
