# https://github.com/elastic/kibana-docker
ARG KIBANA_VERSION
FROM docker.elastic.co/kibana/kibana:${KIBANA_VERSION}

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>

# RUN kibana-plugin install https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.4.2/enhanced-table-1.4.2_7.1.1.zip