---
## Default Kibana configuration from kibana-docker.
## from https://github.com/elastic/kibana-docker/blob/master/build/kibana/config/kibana.yml
#
server.name: kibana
server.host: "0"
server.basePath: "/myapp" # шинч╜о url prefix 
server.rewriteBasePath: true # set true if set basePath for remove url prefix before get in Kibana
# i18n.locale: "zh-CN"
elasticsearch.hosts: [ "http://elasticsearch-node-1:9200" ]
xpack.monitoring.elasticsearch.hosts: [ "http://elasticsearch-node-1:9200" ]
xpack.monitoring.ui.container.elasticsearch.enabled: true
